include $(APPDIR)/Make.defs

PROGNAME = $(CONFIG_MODULES_WEBMORDA_PROGNAME)
PRIORITY = $(CONFIG_MODULES_WEBMORDA_PRIORITY)
STACKSIZE = $(CONFIG_MODULES_WEBMORDA_STACKSIZE)
MODULE = $(CONFIG_MODULES_WEBMORDA)

CXXEXT = .cpp
MAINSRC = webmorda_main.cpp networking/simple_socket.cpp networking/binding_socket.cpp networking/connecting_socket.cpp networking/listening_socket.cpp

include $(APPDIR)/Application.mk
